//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBilling.DataAcces.TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRate
    {
        public int TaxRateId { get; set; }
        public Nullable<int> StateProvinceId { get; set; }
        public Nullable<byte> TaxType { get; set; }
        public Nullable<decimal> TaxRate1 { get; set; }
        public string TaxName { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<int> CreateByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
