//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBilling.Core
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public enum PersonTypeEnum
    {
        User,
        Customer,
        Vendor
    }
    public partial class PersonType
    {

        private PersonType(PersonTypeEnum @enum)
        {
            PersonTypeID = (int)@enum;
            Name = @enum.ToString();
            ModifiedDate = DateTime.Now;
            rowguid = new Guid();
            //this.People = new HashSet<Person>();
        }

        protected PersonType()
        {
        }

        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int PersonTypeID { get; set; }

        [Required, MaxLength(100)]
        public string Name { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }

        public static implicit operator PersonType(PersonTypeEnum @enum) => new PersonType(@enum);

        public static implicit operator PersonTypeEnum(PersonType persontype) => (PersonTypeEnum)persontype.PersonTypeID;

        //public virtual ICollection<Person> People { get; set; }
    }
}
