//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBilling.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        
        public Person()
        {
            this.PersonAddresses = new HashSet<PersonAddress>();
            this.PersonContacts = new HashSet<PersonContact>();
            this.PersonTaxes = new HashSet<PersonTax>();
            this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
            this.PurchaseReceivedChallanHeaders = new HashSet<PurchaseReceivedChallanHeader>();
        }
    
        public int PersonId { get; set; }
        public int PersonTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<int> CreatByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual PersonType PersonType { get; set; }
        
        public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
        
        public virtual ICollection<PersonContact> PersonContacts { get; set; }
        
        public virtual ICollection<PersonTax> PersonTaxes { get; set; }
        
        public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
        
        public virtual ICollection<PurchaseReceivedChallanHeader> PurchaseReceivedChallanHeaders { get; set; }
    }
}
