//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBilling.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderHeader
    {
        
        public PurchaseOrderHeader()
        {
            this.PurchaseReceivedChallanHeaders = new HashSet<PurchaseReceivedChallanHeader>();
        }
    
        public int PurchaseOrderId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TaxAmt { get; set; }
        public decimal Freight { get; set; }
        public decimal TotalDue { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
        
        public virtual ICollection<PurchaseReceivedChallanHeader> PurchaseReceivedChallanHeaders { get; set; }
        public virtual PurchaseOrderTax PurchaseOrderTax { get; set; }
    }
}
